version: 1

sources:
  - name: app_data
    database: "{{env_var('GCLOUD_PROJECT_ID')}}"  
    schema: raw  
    tables:
      - name: distribution_centers
      - name: events
      - name: inventory_items
      - name: order_items
      - name: orders
      - name: products
      - name: users